a=input("Enter your data")
b=a.split(" ")
#print(len(b))
print(b[0])
print(b[1])
print(b[2])
print("------------------")
print(a[2:11].capitalize())
print(a[8:13])
print("-------------------------")
print(b[0])
print(b[1])
print(b[2].upper())
print("--------------------")
print(b[0].upper(),b[1],b[2].upper())

